name: supa_public_feed
description: "Flutter + Supabase + Gemini + PDFs (UI 2025)"
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.10.3
  file_picker: ^10.3.3
  mime: ^1.0.6
  url_launcher: ^6.3.0
  http: ^1.2.2
  google_generative_ai: ^0.4.6
  dynamic_color: ^1.6.9
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
